version = 0.1
[default.deploy.parameters]
stack_name = "semantic-search-web-sockets"
resolve_s3 = true
s3_prefix = "semantic-search-web-sockets"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
image_repositories = []
